controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

user_register:
  path: /api/register
  controller: App\Controller\UserController::register
  methods: [POST]

user_login:
  path: /api/login
  controller: App\Controller\UserController::login
  methods: [POST]

user_getUsers:
  path: /api/getUsers
  controller: App\Controller\UserController::getUsers
  methods: [GET]

api_login_check:
  path: /api/login_check

api_testJWT:
  path: /api/testJWT
  controller: App\Controller\UserController::testJWT

color_insert:
  path: /api/insertar_color
  controller: App\Controller\ColorController::insertarColor
  methods: [POST]

color_get:
  path: /api/getColors
  controller: App\Controller\ColorController::getColors
  methods: [GET]

colorstat_insert:
  path: /api/createColorStat
  controller: App\Controller\ColorStatController::createColorStat
  methods: [POST]

color_topbyclicks:
  path: "/api/colors/topbyclicks"
  controller: 'App\Controller\ColorController::getTopColorsByClicks'
  methods: ["GET"]

color_topbypalettes:
  path: "/api/colors/topbyclicks"
  controller: 'App\Controller\ColorController::getTopColorsByPalettes'
  methods: ["GET"]

color_topbyclicks_username:
  path: "/api/colors/topbyclicks/{username}"
  controller: 'App\Controller\ColorController::getTopColorsByClicksAndUsername'
  methods: ["GET"]

color_topbypalettes_username:
  path: "/api/colors/topbypalettes/{username}"
  controller: 'App\Controller\ColorController::getTopColorsByPalettesAndUsername'
<<<<<<< Updated upstream
  methods: ["GET"]

colorstat_getDates:
  path: /api/getColorDates
  controller: App\Controller\ColorStatController::getColorDates
  methods: [GET]
=======
  methods: ['GET']

palette_gettop:
  path: 'api/getPalettes/Top'
  controller: 'App\Controller\PaletteController::getTopPalettes'
  methods: ['GET']

palette_getbyusername:
  path: 'api/getPalettes/{username}'
  controller: 'App\Controller\PaletteController::getPalettesByUsername'
  methods: ['GET']
>>>>>>> Stashed changes
