controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: [POST]
