controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: [POST]

user_login:
    path: /api/login
    controller: App\Controller\UserController::login
    methods: [POST]
