name: Deploy Docker Container

on:
  push:
    branches:
      - test/runner  # Ajusta el nombre de la rama según tu configuración

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      
    - name: Crear file.txt de prueba
      run: echo "1" | cat >> file.txt

    - name: Crear contenedor 
      run: sudo docker build -t mi_imagen_desde_actions

    - name: Auth
      run: uL6$59mP
    
