name: Deploy Docker Container

on:
  push:
    branches:
      - test/runner  # Ajusta el nombre de la rama según tu configuración

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      
    - name: Crear file.txt de prueba
      run: echo "$USER" | cat >> file.txt
      
    #- name: Crear contenedor desde bash
    #  run: ./scripts/build_container.sh
      
    - name: Crear contenedor 
      run: echo ${{secrets.USER_PASS}} | SUDO_ASKPASS=/bin/echo sudo -S docker ps

    #  run: echo ${{secrets.USER_PASS}} | sudo docker build -t mi_imagen_desde_actions
