name: Deploy Docker Container

on:
  push:
    branches:
      - test/runner  # Ajusta el nombre de la rama según tu configuración

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Iniciar sesión en el servidor
      run: ssh grupo5@146.83.216.166 "echo 'uL6$59mP'"
